server:
  port: 9080
#management:
#  context-path: /spring-manage
#  security:
#    enabled: false
spring:
  application:
    name: aofgo-backend
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: ${dbmode:validate}
    properties:
      hibernate:
        connection:
          CharSet: utf8mb4
          characterEncoding: utf8
          useUnicode: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  datasource:
    url: jdbc:mysql://${dbaddr:mysql}:${dbport:3306}/${dbname:aofgo}?useUnicode=yes&characterEncoding=UTF-8&useSSL=${useSSL:false}
    username: ${dbuser}
    password: ${dbpass}
    dbcp2:
      test-while-idle: true
      validation-query: SET NAMES utf8mb4
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initSQL: "SET NAMES 'utf8mb4'"
  mail:
    from: ${smtpusr:signups@233.com.hk}
    host: mail.codetector.cn
    protocol: smtps
    port: 587
    username: ${smtpusr:signups@233.com.hk}
    password: ${smtppass:}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.transport.protocol: smtps
auth:
  sessionTimeout: 1800